### ISSUE TITLE
Class names component hash looks incorrectly generated

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#162]
Saw this when working on source maps

```
<Style hash=\\"gpurwr\\">{[\\".cc-1b1wq3m{font-size:20px;}
```

Usually the `hash` should be the same as the generated `class`... something might be wrong here.

**Comment by ankeetmaini** [comment]
So I looked through this and found that we're calculating the `className` below (which is set as a string literal immediately) and then updating a closure variable `css`.

```
// before
css = font-size: 20px;
hash = cc-1b1wq3m 
```
https://github.com/atlassian-labs/compiled-css-in-js/blob/9830560bb3e805b77ae05aadc4b139b79cb95536/packages/ts-transform/src/class-names/visitors/visit-class-names-jsx-element.tsx#L45-L48

This `css` is then used inside `createCompiledFragment` to get the hash value and since we've appended the `className`, it results into a different value for `hash` than `className`

```
// after
css = .cc-1b1wq3m { 
            font-size: 20px; }
hash = cc-gpurwr 
```

**Comment by madou** [comment]
ah interesting https://github.com/atlassian-labs/compiled-css-in-js/blob/9830560bb3e805b77ae05aadc4b139b79cb95536/packages/ts-transform/src/utils/create-jsx-element.tsx#L297

thanks for having a dig!
